name: license_reader_flutter
description: "A Flutter app for reading license plates using camera and OCR."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Camera functionality
  camera: ^0.10.5+9
  
  # Image processing and OCR
  google_mlkit_text_recognition: ^0.11.0
  
  # Image picker for selecting images from gallery
  image_picker: ^1.0.7
  
  # Permission handling
  permission_handler: ^11.3.0
  
  # Path provider for file operations
  path_provider: ^2.1.2
  
  # Path for file path operations
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true